openapi: 3.0.3
info:
  title: Margo Workload Management API
  version: 1.0.0
  description: >
    API for managing workloads on Margo-compliant edge devices.
    Communication is secured using server-side TLS (TLS 1.3 preferred),
    and payloads are signed using X.509 certificates.

servers:
  - url: https://wfm.margo.org/api/v1
    description: Workload Fleet Manager API

security:
  - PayloadSignature: []

paths:
  /onboarding/certificate:
    get:
      summary: Download Root CA certificate
      responses:
        '200':
          description: Root CA certificate
          content:
            application/json:
              schema:
                type: object
                properties:
                  certificate:
                    type: string
                    description: Base64-encoded certificate text
  /onboarding:
  post:
    requestBody:
      content:
        application/json:
          schema:
            properties:
              public_certificate:
                description: Base64-encoded client certificate
                type: string
            type: object
      required: true
    responses:
      '200':
        content:
          application/json:
            schema:
              properties:
                client_id:
                  type: string
                endpoints:
                  items:
                    type: string
                  type: array
              type: object
        description: Certificate already present, onboarding successful.
      '201':
        content:
          application/json:
            schema:
              properties:
                client_id:
                  type: string
                endpoints:
                  items:
                    type: string
                  type: array
              type: object
        description: New client onboarded successfully.
      '400':
        content:
          application/json:
            schema:
              properties:
                error:
                  example: Invalid certificate
                  type: string
              type: object
        description: Invalid certificate format or structure.
      '403':
        content:
          application/json:
            schema:
              properties:
                error:
                  example: Client not registered
                  type: string
              type: object
        description: Client certificate not trusted or not registered.
    security:
    - PayloadSignature: []
    summary: Complete onboarding with client certificate

  /client/{clientId}/capabilities:
    post:
      summary: Report device capabilities
      security:
        - PayloadSignature: []
      parameters:
        - name: clientId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceCapabilities'
      responses:
        '201':
          description: Capabilities reported successfully

  /client/{clientId}/deployment/{deploymentId}/status:
    post:
      summary: Report deployment status
      security:
        - PayloadSignature: []
      parameters:
        - name: clientId
          in: path
          required: true
          schema:
            type: string
        - name: deploymentId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeploymentStatus'
      responses:
        '201':
          description: Deployment status updated

components:
  securitySchemes:
    PayloadSignature:
      type: apiKey
      in: header
      name: X-Payload-Signature
      description: >
        Base64-encoded payload signature using SHA-256 and device certificate.
        Format: public_key;digital_signature
  schemas:
    DeviceCapabilities:
      type: object
      required: [apiVersion, kind, properties]
      properties:
        apiVersion:
          type: string
        kind:
          type: string
          enum: [DeviceCapabilities]
        properties:
          type: object
          required: [id, vendor, modelNumber, serialNumber, roles, resources]
          properties:
            id:
              type: string
            vendor:
              type: string
            modelNumber:
              type: string
            serialNumber:
              type: string
            roles:
              type: array
              items:
                type: string
                enum: [Standalone Cluster, Cluster Leader, Standalone Device]
            resources:
              type: object
              required: [cpu, memory, storage]
              properties:
                cpu:
                  type: object
                  properties:
                    cores:
                      type: number
                memory:
                  type: string
                storage:
                  type: string

    DeploymentStatus:
      type: object
      required: [apiVersion, kind, deploymentId, status, components]
      properties:
        apiVersion:
          type: string
        kind:
          type: string
          enum: [DeploymentStatus]
        deploymentId:
          type: string
        status:
          type: object
          required: [state]
          properties:
            state:
              type: string
              enum: [Pending, Installing, Installed, Failed]
            error:
              type: object
              properties:
                code:
                  type: string
                message:
                  type: string
        components:
          type: array
          items:
            type: object
            required: [name, state]
            properties:
              name:
                type: string
              state:
                type: string
                enum: [Pending, Installing, Installed, Failed]
              error:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
